export enum AuthEnum {
  AUTH = 'AUTH',
  LOAD = 'AUTH_LOAD',
  LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS',
  LOAD_FAILURE = 'AUTH_LOAD_FAILURE',
  AUTH_PENDING = 'AUTH_PENDING',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILURE = 'AUTH_FAILURE',
  LOGOUT = 'AUTH_LOGOUT'
}