export enum GroupEnum {
  START_LOADING = 'GROUP_START_LOADING',
  STOP_LOADING = 'GROUP_STOP_LOADING',
  SET = 'GROUP_SET',
  SET_FIX = 'GROUP_SET_FIX',
  CLEAR_SET = 'GROUP_CLEAR_SET',
  FETCH = 'GROUP_FETCH',
  FETCH_PENDING = 'GROUP_FETCH_PENDING',
  FETCH_SUCCESS = 'GROUP_FETCH_SUCCESS',
  FETCH_FAILURE = 'GROUP_FETCH_FAILURE',
}
